version: "3.8"
   
services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations accounts posts && python manage.py migrate && python manage.py loaddata exercise-data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: always
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: always