version: "3.8"
   
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python manage.py makemigrations accounts posts && python manage.py migrate && python manage.py loaddata exercise-data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always