export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const AUTO_SIGNIN = 'AUTO_SIGNIN';
export const ONBOARDING = 'ONBOARDING';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
