export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const AUTO_SIGNIN = 'AUTO_SIGNIN';
export const SIGNUP = 'SIGNUP';
export const GET_USER_NOTIFICATION = 'GET_USER_NOTIFICATION';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
